//
// CharityDonationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Donation instructions */
public struct CharityDonationRequest: Codable, JSONEncodable, Hashable {

    /** Fixed-point decimal number, carried up to two decimal places. */
    public var amount: Double

    public init(amount: Double) {
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
    }
}

