//
// CharityRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Filter for Charity a customer can donate to. */
public struct CharityRequest: Codable, JSONEncodable, Hashable {

    /** Search query term for a Charity lookup by ID, name or EIN. */
    public var query: String
    public var sortOrder: [SortOrder]?

    public init(query: String, sortOrder: [SortOrder]? = nil) {
        self.query = query
        self.sortOrder = sortOrder
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case query
        case sortOrder
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(query, forKey: .query)
        try container.encodeIfPresent(sortOrder, forKey: .sortOrder)
    }
}

