//
// CharityDonation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CharityDonation: Codable, JSONEncodable, Hashable {

    public var charity: Charity
    /** Dollar value donated to the charity. */
    public var amountDonated: Double

    public init(charity: Charity, amountDonated: Double) {
        self.charity = charity
        self.amountDonated = amountDonated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case charity
        case amountDonated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(charity, forKey: .charity)
        try container.encode(amountDonated, forKey: .amountDonated)
    }
}

