//
// ClientSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientSettings: Codable, JSONEncodable, Hashable {

    /** Hierarchical order of brand colors in HTML/CSS values */
    public var brandColors: [String]?
    public var rewardSettings: RewardSettings
    public var customerLimits: CustomerLimits
    public var rewardCategorySelections: [InstantImpactCategoryRewardSelection]?

    public init(brandColors: [String]? = nil, rewardSettings: RewardSettings, customerLimits: CustomerLimits, rewardCategorySelections: [InstantImpactCategoryRewardSelection]? = nil) {
        self.brandColors = brandColors
        self.rewardSettings = rewardSettings
        self.customerLimits = customerLimits
        self.rewardCategorySelections = rewardCategorySelections
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case brandColors
        case rewardSettings
        case customerLimits
        case rewardCategorySelections
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(brandColors, forKey: .brandColors)
        try container.encode(rewardSettings, forKey: .rewardSettings)
        try container.encode(customerLimits, forKey: .customerLimits)
        try container.encodeIfPresent(rewardCategorySelections, forKey: .rewardCategorySelections)
    }
}

