//
// GenericCardType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Unique type for the UI card. */
public enum GenericCardType: String, Codable, CaseIterable {
    case srSummary = "SR_SUMMARY"
}
