//
// GivingCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GivingCategory: Codable, JSONEncodable, Hashable {

    /** Unique ID of the charity category. */
    public var id: String?
    /** Name of the charity category. */
    public var name: String
    /** Background image. */
    public var backgroundImageUrl: String?
    /** Unique ID of the charity category (only returned for getCharityCategories). */
    public var charities: [Charity]?

    public init(id: String? = nil, name: String, backgroundImageUrl: String? = nil, charities: [Charity]? = nil) {
        self.id = id
        self.name = name
        self.backgroundImageUrl = backgroundImageUrl
        self.charities = charities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case backgroundImageUrl
        case charities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(backgroundImageUrl, forKey: .backgroundImageUrl)
        try container.encodeIfPresent(charities, forKey: .charities)
    }
}

