//
// InstantImpactCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Instant Impact Category */
public struct InstantImpactCategory: Codable, JSONEncodable, Hashable {

    /** Unique ID of the charity category. */
    public var id: String?
    /** Name of the charity category. */
    public var name: String
    /** Id of the default charity for this category. Charity can be found under charities field. */
    public var defaultCharityId: String?
    public var charities: [Charity]?

    public init(id: String? = nil, name: String, defaultCharityId: String? = nil, charities: [Charity]? = nil) {
        self.id = id
        self.name = name
        self.defaultCharityId = defaultCharityId
        self.charities = charities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case defaultCharityId
        case charities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(defaultCharityId, forKey: .defaultCharityId)
        try container.encodeIfPresent(charities, forKey: .charities)
    }
}

