//
// RegistrationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegistrationRequest: Codable, JSONEncodable, Hashable {

    /** Invite Code */
    public var inviteCode: String
    public var user: User

    public init(inviteCode: String, user: User) {
        self.inviteCode = inviteCode
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inviteCode
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(inviteCode, forKey: .inviteCode)
        try container.encode(user, forKey: .user)
    }
}

