//
// SocialResponsibilityInstantImpactCardResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Generic card response */
public struct SocialResponsibilityInstantImpactCardResponse: Codable, JSONEncodable {

    /** Generic card JSON */
    public var card: GenericCardModel

    public init(card: GenericCardModel) {
        self.card = card
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case card
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(card, forKey: .card)
    }
}

