//
// SortOrder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SortOrder: Codable, JSONEncodable, Hashable {

    public enum Order: String, Codable, CaseIterable {
        case asc = "asc"
        case desc = "desc"
    }
    /** Field name to sort by */
    public var field: String
    /** Sort order */
    public var order: Order

    public init(field: String, order: Order) {
        self.field = field
        self.order = order
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case field
        case order
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(field, forKey: .field)
        try container.encode(order, forKey: .order)
    }
}

