//
// TransactionInstantImpactSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionInstantImpactSummary: Codable, JSONEncodable, Hashable {

    public var categoryId: String?
    /** Name of the charity category. */
    public var categoryName: String?
    /** Reward Unit key */
    public var rewardUnitName: String?
    /** Aggregated point value for associated Instant Impact Category. */
    public var totalImpact: Double?
    /** Aggregated dollar value for associated Instant Impact Category. */
    public var totalDonatedAmount: Double?

    public init(categoryId: String? = nil, categoryName: String? = nil, rewardUnitName: String? = nil, totalImpact: Double? = nil, totalDonatedAmount: Double? = nil) {
        self.categoryId = categoryId
        self.categoryName = categoryName
        self.rewardUnitName = rewardUnitName
        self.totalImpact = totalImpact
        self.totalDonatedAmount = totalDonatedAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categoryId
        case categoryName
        case rewardUnitName
        case totalImpact
        case totalDonatedAmount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(categoryId, forKey: .categoryId)
        try container.encodeIfPresent(categoryName, forKey: .categoryName)
        try container.encodeIfPresent(rewardUnitName, forKey: .rewardUnitName)
        try container.encodeIfPresent(totalImpact, forKey: .totalImpact)
        try container.encodeIfPresent(totalDonatedAmount, forKey: .totalDonatedAmount)
    }
}

