//
// TransactionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionResponse: Codable, JSONEncodable, Hashable {

    /** Permanent, unique transaction id. Must survive changes to pending status or amount. */
    public var transactionId: String
    public var instantImpact: TransactionInstantImpact
    public var rewardSettings: RewardSettings

    public init(transactionId: String, instantImpact: TransactionInstantImpact, rewardSettings: RewardSettings) {
        self.transactionId = transactionId
        self.instantImpact = instantImpact
        self.rewardSettings = rewardSettings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transactionId
        case instantImpact
        case rewardSettings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(transactionId, forKey: .transactionId)
        try container.encode(instantImpact, forKey: .instantImpact)
        try container.encode(rewardSettings, forKey: .rewardSettings)
    }
}

