//
// ActionNotificationResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ActionNotificationResponseAllOf: Codable, JSONEncodable, Hashable {

    /** Does notification require customer action */
    public var isActionable: Bool

    public init(isActionable: Bool) {
        self.isActionable = isActionable
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isActionable
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isActionable, forKey: .isActionable)
    }
}

