//
// ActionNotificationsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ActionNotificationsResponse: Codable, JSONEncodable, Hashable {

    public var notifications: [ActionNotificationResponse]

    public init(notifications: [ActionNotificationResponse]) {
        self.notifications = notifications
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notifications
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(notifications, forKey: .notifications)
    }
}

