//
// AuditClient.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuditClient: Codable, JSONEncodable, Hashable {

    /** Spiral generated unique Client ID */
    public var id: String?
    /** URL within Cloudinary */
    public var logo: String?
    /** Full fintech name */
    public var fintechName: String
    /** Starting timestamp of the fintech's contract. */
    public var contractStart: Int64?
    /** Ending timestamp of the fintech's contract. */
    public var contractEnd: Int64?
    /** Spiral-side manager assigned to this client. */
    public var manager: String?

    public init(id: String? = nil, logo: String? = nil, fintechName: String, contractStart: Int64? = nil, contractEnd: Int64? = nil, manager: String? = nil) {
        self.id = id
        self.logo = logo
        self.fintechName = fintechName
        self.contractStart = contractStart
        self.contractEnd = contractEnd
        self.manager = manager
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case logo
        case fintechName
        case contractStart
        case contractEnd
        case manager
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(logo, forKey: .logo)
        try container.encode(fintechName, forKey: .fintechName)
        try container.encodeIfPresent(contractStart, forKey: .contractStart)
        try container.encodeIfPresent(contractEnd, forKey: .contractEnd)
        try container.encodeIfPresent(manager, forKey: .manager)
    }
}

