//
// AuditEventType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Unique type of an audit event */
public enum AuditEventType: String, Codable, CaseIterable {
    case insert = "INSERT"
    case update = "UPDATE"
    case delete = "DELETE"
}
