//
// AuditEventType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Unique type of an audit event */
public enum AuditEventType: String, Codable, CaseIterable {
    case inserted = "INSERTED"
    case updated = "UPDATED"
    case deleted = "DELETED"
}
