//
// AuditClient.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuditClient: Codable, JSONEncodable, Hashable {

    /** Spiral generated unique Client ID */
    public var id: String?
    /** URL within Cloudinary */
    public var logo: String?
    /** Full fintech name */
    public var fintechName: String

    public init(id: String? = nil, logo: String? = nil, fintechName: String) {
        self.id = id
        self.logo = logo
        self.fintechName = fintechName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case logo
        case fintechName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(logo, forKey: .logo)
        try container.encode(fintechName, forKey: .fintechName)
    }
}

