//
// CharityDonationReportRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CharityDonationReportRequest: Codable, JSONEncodable, Hashable {

    /** Start time filter. Also used to wrap the month and year for monthly reports. */
    public var from: Date
    /** End time filter. Also used to wrap the month and year for monthly reports. */
    public var to: Date
    /** Charity unique Employer Identification Number (EIN) */
    public var ein: String?

    public init(from: Date, to: Date, ein: String? = nil) {
        self.from = from
        self.to = to
        self.ein = ein
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case from
        case to
        case ein
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(from, forKey: .from)
        try container.encode(to, forKey: .to)
        try container.encodeIfPresent(ein, forKey: .ein)
    }
}

