//
// ClientGivingCharitySettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Client settings for Charities in Giving Portal */
public struct ClientGivingCharitySettings: Codable, JSONEncodable, Hashable {

    public var excluded: ClientGivingExcludedCharitySettings?
    /** List of Charity IDs to be highlighted in giving portal search */
    public var highlighted: [String]?

    public init(excluded: ClientGivingExcludedCharitySettings? = nil, highlighted: [String]? = nil) {
        self.excluded = excluded
        self.highlighted = highlighted
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case excluded
        case highlighted
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(excluded, forKey: .excluded)
        try container.encodeIfPresent(highlighted, forKey: .highlighted)
    }
}

