//
// ClientAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientAllOf: Codable, JSONEncodable, Hashable {

    /** Shortname description of the fintech brand */
    public var brandName: String?
    public var contactUser: User?
    public var clientSettings: ClientSettings?
    public var products: ClientProducts

    public init(brandName: String? = nil, contactUser: User? = nil, clientSettings: ClientSettings? = nil, products: ClientProducts) {
        self.brandName = brandName
        self.contactUser = contactUser
        self.clientSettings = clientSettings
        self.products = products
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case brandName
        case contactUser
        case clientSettings
        case products
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(brandName, forKey: .brandName)
        try container.encodeIfPresent(contactUser, forKey: .contactUser)
        try container.encodeIfPresent(clientSettings, forKey: .clientSettings)
        try container.encode(products, forKey: .products)
    }
}

