//
// ClientFont.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientFont: Codable, JSONEncodable, Hashable {

    /** The font's name */
    public var font: String
    public var type: ClientFontType

    public init(font: String, type: ClientFontType) {
        self.font = font
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case font
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(font, forKey: .font)
        try container.encode(type, forKey: .type)
    }
}

