//
// ClientGivingSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Client settings for Giving Portal */
public struct ClientGivingSettings: Codable, JSONEncodable, Hashable {

    public var charitySettings: ClientGivingCharitySettings?

    public init(charitySettings: ClientGivingCharitySettings? = nil) {
        self.charitySettings = charitySettings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case charitySettings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(charitySettings, forKey: .charitySettings)
    }
}

