//
// ClientUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientUpdateRequest: Codable, JSONEncodable, Hashable {

    public var client: ClientUpdate

    public init(client: ClientUpdate) {
        self.client = client
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case client
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(client, forKey: .client)
    }
}

