//
// ClientGivingExcludedCharitySettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientGivingExcludedCharitySettings: Codable, JSONEncodable, Hashable {

    /** List of Charity IDs excluded from being recommended in the giving portal */
    public var recommended: [String]?
    /** List of Charity IDs excluded from the giving portal search */
    public var search: [String]?

    public init(recommended: [String]? = nil, search: [String]? = nil) {
        self.recommended = recommended
        self.search = search
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recommended
        case search
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(recommended, forKey: .recommended)
        try container.encodeIfPresent(search, forKey: .search)
    }
}

