//
// ClientFonts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientFonts: Codable, JSONEncodable, Hashable {

    public var headingFont: ClientFont?
    public var bodyFont: ClientFont?

    public init(headingFont: ClientFont? = nil, bodyFont: ClientFont? = nil) {
        self.headingFont = headingFont
        self.bodyFont = bodyFont
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case headingFont
        case bodyFont
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(headingFont, forKey: .headingFont)
        try container.encodeIfPresent(bodyFont, forKey: .bodyFont)
    }
}

