//
// ClientProducts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientProducts: Codable, JSONEncodable, Hashable {

    /** Clients instant impact product on/off */
    public var instantImpact: Bool = false
    /** Clients giving product on/off */
    public var giving: Bool = false
    /** Clients DAF product on/off */
    public var daf: Bool = false

    public init(instantImpact: Bool = false, giving: Bool = false, daf: Bool = false) {
        self.instantImpact = instantImpact
        self.giving = giving
        self.daf = daf
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case instantImpact
        case giving
        case daf
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(instantImpact, forKey: .instantImpact)
        try container.encode(giving, forKey: .giving)
        try container.encode(daf, forKey: .daf)
    }
}

