//
// ClientDonationListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientDonationListResponse: Codable, JSONEncodable, Hashable {

    /** The count of all donations across all pages. */
    public var totalDonations: Double
    /** The count of all donations on this page. */
    public var pageDonations: Double
    /** The total summed amount of all donations across all pages. */
    public var totalAmount: Double
    /** The summed amount of all donations on this page. */
    public var pageAmount: Double
    public var donations: [ClientDonationResponse]

    public init(totalDonations: Double, pageDonations: Double, totalAmount: Double, pageAmount: Double, donations: [ClientDonationResponse]) {
        self.totalDonations = totalDonations
        self.pageDonations = pageDonations
        self.totalAmount = totalAmount
        self.pageAmount = pageAmount
        self.donations = donations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalDonations
        case pageDonations
        case totalAmount
        case pageAmount
        case donations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(totalDonations, forKey: .totalDonations)
        try container.encode(pageDonations, forKey: .pageDonations)
        try container.encode(totalAmount, forKey: .totalAmount)
        try container.encode(pageAmount, forKey: .pageAmount)
        try container.encode(donations, forKey: .donations)
    }
}

