//
// CreateAnalyticsEventBatchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAnalyticsEventBatchRequest: Codable, JSONEncodable, Hashable {

    public var events: [CreateAnalyticsEventRequest]

    public init(events: [CreateAnalyticsEventRequest]) {
        self.events = events
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case events
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(events, forKey: .events)
    }
}

