//
// CreateLogEntryRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateLogEntryRequest: Codable, JSONEncodable, Hashable {

    public var level: LogLevel?
    /** The log message */
    public var message: String?

    public init(level: LogLevel? = nil, message: String? = nil) {
        self.level = level
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case level
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(level, forKey: .level)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

