//
// CstOperationsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CstOperationsResponse: Codable, JSONEncodable, Hashable {

    public var action: OperationsCenterAction
    /** ID of the item this operation was on. */
    public var operationItemId: String
    /** Attached operation reason. Usually a failure reason. */
    public var reason: String?

    public init(action: OperationsCenterAction, operationItemId: String, reason: String? = nil) {
        self.action = action
        self.operationItemId = operationItemId
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case operationItemId
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encode(operationItemId, forKey: .operationItemId)
        try container.encodeIfPresent(reason, forKey: .reason)
    }
}

