//
// CstOperationsResponseList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CstOperationsResponseList: Codable, JSONEncodable, Hashable {

    /** List of successfully passed operation item IDs. */
    public var successfulOperations: [CstOperationsResponse]
    /** List of failed operation item IDs with their failure reasons */
    public var failedOperations: [CstOperationsResponse]

    public init(successfulOperations: [CstOperationsResponse], failedOperations: [CstOperationsResponse]) {
        self.successfulOperations = successfulOperations
        self.failedOperations = failedOperations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case successfulOperations
        case failedOperations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(successfulOperations, forKey: .successfulOperations)
        try container.encode(failedOperations, forKey: .failedOperations)
    }
}

