//
// CustomerInstantImpactLimitSelections.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Available selections for the customer instant impact limit */
public enum CustomerInstantImpactLimitSelections: String, Codable, CaseIterable {
    case daily = "daily"
    case weekly = "weekly"
    case monthly = "monthly"
    case noLimit = "no_limit"
}
