//
// CustomerLimits.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomerLimits: Codable, JSONEncodable, Hashable {

    public var percentageUpperLimit: Int?
    public var totalMonthlyCap: Int?
    public var onTransactionsOver: Int?
    public var onTransactionsUnder: Int?

    public init(percentageUpperLimit: Int? = nil, totalMonthlyCap: Int? = nil, onTransactionsOver: Int? = nil, onTransactionsUnder: Int? = nil) {
        self.percentageUpperLimit = percentageUpperLimit
        self.totalMonthlyCap = totalMonthlyCap
        self.onTransactionsOver = onTransactionsOver
        self.onTransactionsUnder = onTransactionsUnder
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case percentageUpperLimit
        case totalMonthlyCap
        case onTransactionsOver
        case onTransactionsUnder
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(percentageUpperLimit, forKey: .percentageUpperLimit)
        try container.encodeIfPresent(totalMonthlyCap, forKey: .totalMonthlyCap)
        try container.encodeIfPresent(onTransactionsOver, forKey: .onTransactionsOver)
        try container.encodeIfPresent(onTransactionsUnder, forKey: .onTransactionsUnder)
    }
}

