//
// DepositoryOrCreditTransactionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Classification of DepositoryOrCredit by purpose as an enum. */
public enum DepositoryOrCreditTransactionType: String, Codable, CaseIterable {
    case transfer = "transfer"
    case cash = "cash"
    case fee = "fee"
    case purchase = "purchase"
    case interest = "interest"
    case deposit = "deposit"
}
