//
// DonationReceiptAnnualDetailedSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DonationReceiptAnnualDetailedSummary: Codable, JSONEncodable, Hashable {

    /** Year number */
    public var year: Int
    /** List of month simple summaries */
    public var months: [DonationReceiptMonthlySimpleSummary]

    public init(year: Int, months: [DonationReceiptMonthlySimpleSummary]) {
        self.year = year
        self.months = months
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case year
        case months
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(year, forKey: .year)
        try container.encode(months, forKey: .months)
    }
}

