//
// DonationReceiptMonthlyDetailedSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DonationReceiptMonthlyDetailedSummary: Codable, JSONEncodable, Hashable {

    /** Year number */
    public var year: Int?
    /** Month number */
    public var month: Int
    /** List of donations grouped by charity */
    public var charities: [DonationReceiptCharityElement]?

    public init(year: Int? = nil, month: Int, charities: [DonationReceiptCharityElement]? = nil) {
        self.year = year
        self.month = month
        self.charities = charities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case year
        case month
        case charities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encode(month, forKey: .month)
        try container.encodeIfPresent(charities, forKey: .charities)
    }
}

