//
// DonationReceiptSummarySimpleElementType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Donation Receipt summary simple list element type */
public enum DonationReceiptSummarySimpleElementType: String, Codable, CaseIterable {
    case giving = "GIVING"
    case everydayImpact = "EVERYDAY_IMPACT"
    case eoyGivingReport = "EOY_GIVING_REPORT"
}
