//
// DonationType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Donation Type */
public enum DonationType: String, Codable, CaseIterable {
    case oneTime = "ONE_TIME"
    case recurring = "RECURRING"
    case everydayImpact = "EVERYDAY_IMPACT"
}
