//
// DonationReceiptCharityDonationElement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DonationReceiptCharityDonationElement: Codable, JSONEncodable, Hashable {

    public var type: DonationType
    /** Unique Receipt ID */
    public var id: String
    /** Creation date */
    public var createdAtDate: Date?

    public init(type: DonationType, id: String, createdAtDate: Date? = nil) {
        self.type = type
        self.id = id
        self.createdAtDate = createdAtDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case id
        case createdAtDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(createdAtDate, forKey: .createdAtDate)
    }
}

