//
// DonationReceiptMonthlySimpleSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DonationReceiptMonthlySimpleSummary: Codable, JSONEncodable, Hashable {

    /** Month number */
    public var month: Int
    /** List of months donation summary grouped by product */
    public var content: [DonationReceiptSummarySimpleElement]

    public init(month: Int, content: [DonationReceiptSummarySimpleElement]) {
        self.month = month
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case month
        case content
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(month, forKey: .month)
        try container.encode(content, forKey: .content)
    }
}

