//
// ExtendedImpactCategoryRewardSelectionAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExtendedImpactCategoryRewardSelectionAllOf: Codable, JSONEncodable, Hashable {

    /** Name of the reward unit */
    public var rewardUnitName: String
    /** Is Impact Category enabled for a customer */
    public var enabled: Bool?

    public init(rewardUnitName: String, enabled: Bool? = nil) {
        self.rewardUnitName = rewardUnitName
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rewardUnitName
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rewardUnitName, forKey: .rewardUnitName)
        try container.encodeIfPresent(enabled, forKey: .enabled)
    }
}

