//
// GenericTemplateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Generic template response */
public struct GenericTemplateResponse: Codable, JSONEncodable, Hashable {

    /** Generic template JSON */
    public var template: AnyCodable

    public init(template: AnyCodable) {
        self.template = template
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case template
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(template, forKey: .template)
    }
}

