//
// GenericTemplateType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Unique type for the UI card. */
public enum GenericTemplateType: String, Codable, CaseIterable {
    case srSummary = "SR_SUMMARY"
    case howItWorks = "HOW_IT_WORKS"
    case userSponsoredOptIn = "USER_SPONSORED_OPT_IN"
    case donationFeeDisclosure = "DONATION_FEE_DISCLOSURE"
    case donationFeeSuccess = "DONATION_FEE_SUCCESS"
    case sgnDonationFeeDisclosure = "SGN_DONATION_FEE_DISCLOSURE"
    case sgnDonationFeeSuccess = "SGN_DONATION_FEE_SUCCESS"
    case notificationDonationReceived = "NOTIFICATION_DONATION_RECEIVED"
    case notificationDetailsDonationReceived = "NOTIFICATION_DETAILS_DONATION_RECEIVED"
    case notificationDonationCharityUpdate = "NOTIFICATION_DONATION_CHARITY_UPDATE"
    case notificationDetailsDonationCharityUpdate = "NOTIFICATION_DETAILS_DONATION_CHARITY_UPDATE"
    case notificationDonationCharityAlternativeSelected = "NOTIFICATION_DONATION_CHARITY_ALTERNATIVE_SELECTED"
    case notificationDetailsDonationCharityAlternativeSelected = "NOTIFICATION_DETAILS_DONATION_CHARITY_ALTERNATIVE_SELECTED"
    case notificationDonationUnableToProcess = "NOTIFICATION_DONATION_UNABLE_TO_PROCESS"
    case notificationDetailsDonationUnableToProcess = "NOTIFICATION_DETAILS_DONATION_UNABLE_TO_PROCESS"
    case sgnEverydayImpactDonationFeeDisclosure = "SGN_EVERYDAY_IMPACT_DONATION_FEE_DISCLOSURE"
    case sgnUnderstandMyDonation = "SGN_UNDERSTAND_MY_DONATION"
}
