//
// GeoCoordinates.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Geographic coordinates in EPSG:4326 WGS84 (lat/long) */
public struct GeoCoordinates: Codable, JSONEncodable, Hashable {

    /** Latitude coordinate. */
    public var lat: Double?
    /** Longitude coordinate. */
    public var lon: Double?

    public init(lat: Double? = nil, lon: Double? = nil) {
        self.lat = lat
        self.lon = lon
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lat
        case lon
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(lat, forKey: .lat)
        try container.encodeIfPresent(lon, forKey: .lon)
    }
}

