//
// GivingCustomerCharityRecurringDonationResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GivingCustomerCharityRecurringDonationResponseAllOf: Codable, JSONEncodable, Hashable {

    /** Recurring donations icon url */
    public var iconUrl: String?

    public init(iconUrl: String? = nil) {
        self.iconUrl = iconUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case iconUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(iconUrl, forKey: .iconUrl)
    }
}

