//
// GivingCustomerCharityDonationsSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GivingCustomerCharityDonationsSummary: Codable, JSONEncodable, Hashable {

    /** Charity ID */
    public var charityId: String
    /** One time donations icon url */
    public var iconUrl: String?
    /** Total amount of donations */
    public var totalDonatedAmount: Double

    public init(charityId: String, iconUrl: String? = nil, totalDonatedAmount: Double) {
        self.charityId = charityId
        self.iconUrl = iconUrl
        self.totalDonatedAmount = totalDonatedAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case charityId
        case iconUrl
        case totalDonatedAmount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(charityId, forKey: .charityId)
        try container.encodeIfPresent(iconUrl, forKey: .iconUrl)
        try container.encode(totalDonatedAmount, forKey: .totalDonatedAmount)
    }
}

