//
// GivingCustomerDonationReceiptSummaryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GivingCustomerDonationReceiptSummaryResponse: Codable, JSONEncodable, Hashable {

    public var currentYear: DonationReceiptAnnualDetailedSummary
    /** List of summaries for past years */
    public var pastYears: [DonationReceiptAnnualSimpleSummary]

    public init(currentYear: DonationReceiptAnnualDetailedSummary, pastYears: [DonationReceiptAnnualSimpleSummary]) {
        self.currentYear = currentYear
        self.pastYears = pastYears
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currentYear
        case pastYears
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currentYear, forKey: .currentYear)
        try container.encode(pastYears, forKey: .pastYears)
    }
}

