//
// GivingCustomerCharityResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Charity details along with customer donation info */
public struct GivingCustomerCharityResponse: Codable, JSONEncodable, Hashable {

    public var charity: GivingCharityResponse
    public var donations: GivingCustomerCharityDonationsResponse?

    public init(charity: GivingCharityResponse, donations: GivingCustomerCharityDonationsResponse? = nil) {
        self.charity = charity
        self.donations = donations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case charity
        case donations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(charity, forKey: .charity)
        try container.encodeIfPresent(donations, forKey: .donations)
    }
}

