//
// GivingCharitiesSearchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Search result for Charities */
public struct GivingCharitiesSearchResponse: Codable, JSONEncodable, Hashable {

    public var filter: GivingCharitiesSearchRequest?
    public var charities: [GivingCharityResponse]?

    public init(filter: GivingCharitiesSearchRequest? = nil, charities: [GivingCharityResponse]? = nil) {
        self.filter = filter
        self.charities = charities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filter
        case charities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(filter, forKey: .filter)
        try container.encodeIfPresent(charities, forKey: .charities)
    }
}

