//
// GivingCharitiesByIdRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** List of Charity IDs to get details for */
public struct GivingCharitiesByIdRequest: Codable, JSONEncodable, Hashable {

    /** List of Charities IDs */
    public var charities: [String]

    public init(charities: [String]) {
        self.charities = charities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case charities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(charities, forKey: .charities)
    }
}

