//
// GivingCharityResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GivingCharityResponse: Codable, JSONEncodable, Hashable {

    /** Unique ID of giving charity */
    public var id: String
    /** Name of the giving charity */
    public var name: String
    /** Unique EIN of giving charity */
    public var ein: String
    /** Short description of giving charity */
    public var description: String?
    /** List of categories giving charity is assigned to */
    public var categories: [GivingCharityCategory]?
    /** List of giving charity images */
    public var images: [CharityImage]?

    public init(id: String, name: String, ein: String, description: String? = nil, categories: [GivingCharityCategory]? = nil, images: [CharityImage]? = nil) {
        self.id = id
        self.name = name
        self.ein = ein
        self.description = description
        self.categories = categories
        self.images = images
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case ein
        case description
        case categories
        case images
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(ein, forKey: .ein)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(categories, forKey: .categories)
        try container.encodeIfPresent(images, forKey: .images)
    }
}

