//
// GivingCustomerDonationReceiptSummaryReceipt.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GivingCustomerDonationReceiptSummaryReceipt: Codable, JSONEncodable, Hashable {

    /** Receipt ID */
    public var id: String
    /** Timestamp of the receipt */
    public var date: Double
    /** Recipient charity name */
    public var charityName: String
    /** Donation period - one-time or monthly */
    public var period: String
    /** Whether the receipt has been processed and is ready for viewing */
    public var ready: Bool

    public init(id: String, date: Double, charityName: String, period: String, ready: Bool) {
        self.id = id
        self.date = date
        self.charityName = charityName
        self.period = period
        self.ready = ready
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case date
        case charityName
        case period
        case ready
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(date, forKey: .date)
        try container.encode(charityName, forKey: .charityName)
        try container.encode(period, forKey: .period)
        try container.encode(ready, forKey: .ready)
    }
}

