//
// GivingCustomerDonationReceiptSummaryMonth.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GivingCustomerDonationReceiptSummaryMonth: Codable, JSONEncodable, Hashable {

    /** The given month */
    public var month: String
    /** Title to display in the summary list */
    public var title: String
    /** List of grouped receipts for the given month, based on the provided grouping setting */
    public var groups: [GivingCustomerDonationReceiptSummaryGroup]

    public init(month: String, title: String, groups: [GivingCustomerDonationReceiptSummaryGroup]) {
        self.month = month
        self.title = title
        self.groups = groups
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case month
        case title
        case groups
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(month, forKey: .month)
        try container.encode(title, forKey: .title)
        try container.encode(groups, forKey: .groups)
    }
}

