//
// GivingCharityResponseWrapper.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response object for a single Charity */
public struct GivingCharityResponseWrapper: Codable, JSONEncodable, Hashable {

    public var charity: GivingCharityResponse

    public init(charity: GivingCharityResponse) {
        self.charity = charity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case charity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(charity, forKey: .charity)
    }
}

