//
// GivingCharityCategoriesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Search result for Charity Categories */
public struct GivingCharityCategoriesResponse: Codable, JSONEncodable, Hashable {

    public var categories: [GivingCharityCategoryResponse]

    public init(categories: [GivingCharityCategoryResponse]) {
        self.categories = categories
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categories
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(categories, forKey: .categories)
    }
}

