//
// GivingCustomerRecurringCharityDonationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Customer giving recurring charity donation */
public struct GivingCustomerRecurringCharityDonationResponse: Codable, JSONEncodable, Hashable {

    public var charity: GivingCharityResponse?
    /** Is recurring donation paused */
    public var paused: Bool?
    /** Recurring donation amount */
    public var amount: Double?
    /** Recurring donation id */
    public var id: String?

    public init(charity: GivingCharityResponse? = nil, paused: Bool? = nil, amount: Double? = nil, id: String? = nil) {
        self.charity = charity
        self.paused = paused
        self.amount = amount
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case charity
        case paused
        case amount
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(charity, forKey: .charity)
        try container.encodeIfPresent(paused, forKey: .paused)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(id, forKey: .id)
    }
}

