//
// GivingCustomerDonationReceiptSummaryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GivingCustomerDonationReceiptSummaryResponse: Codable, JSONEncodable, Hashable {

    /** List of years that donation receipt summary is available for */
    public var years: [GivingCustomerDonationReceiptSummaryYear]

    public init(years: [GivingCustomerDonationReceiptSummaryYear]) {
        self.years = years
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case years
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(years, forKey: .years)
    }
}

