//
// GivingCustomerDonationsSummaryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Customer giving donations summary for given time period */
public struct GivingCustomerDonationsSummaryResponse: Codable, JSONEncodable, Hashable {

    /** Has customer ever donated to any charities */
    public var everDonated: Bool
    public var periodTotal: GivingCustomerDonationsSummaryItem
    public var recurring: GivingCustomerDonationsSummaryItem
    public var oneTime: GivingCustomerDonationsSummaryItem
    public var allTime: GivingCustomerDonationsSummaryItem

    public init(everDonated: Bool, periodTotal: GivingCustomerDonationsSummaryItem, recurring: GivingCustomerDonationsSummaryItem, oneTime: GivingCustomerDonationsSummaryItem, allTime: GivingCustomerDonationsSummaryItem) {
        self.everDonated = everDonated
        self.periodTotal = periodTotal
        self.recurring = recurring
        self.oneTime = oneTime
        self.allTime = allTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case everDonated
        case periodTotal
        case recurring
        case oneTime
        case allTime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(everDonated, forKey: .everDonated)
        try container.encode(periodTotal, forKey: .periodTotal)
        try container.encode(recurring, forKey: .recurring)
        try container.encode(oneTime, forKey: .oneTime)
        try container.encode(allTime, forKey: .allTime)
    }
}

