//
// GivingCharityRecurringDonationResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GivingCharityRecurringDonationResponseAllOf: Codable, JSONEncodable, Hashable {

    /** Recurring donation ID */
    public var id: String?
    /** Next donation date as timestamp */
    public var nextDate: Int64?

    public init(id: String? = nil, nextDate: Int64? = nil) {
        self.id = id
        self.nextDate = nextDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case nextDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(nextDate, forKey: .nextDate)
    }
}

