//
// GivingCustomerDonationsSummaryItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Customer giving donations summary item */
public struct GivingCustomerDonationsSummaryItem: Codable, JSONEncodable, Hashable {

    /** Icon url for this item */
    public var iconUrl: String?
    /** Amount donated */
    public var donatedAmount: Double

    public init(iconUrl: String? = nil, donatedAmount: Double) {
        self.iconUrl = iconUrl
        self.donatedAmount = donatedAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case iconUrl
        case donatedAmount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(iconUrl, forKey: .iconUrl)
        try container.encode(donatedAmount, forKey: .donatedAmount)
    }
}

