//
// GivingCustomerDonationReceiptSummaryYear.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GivingCustomerDonationReceiptSummaryYear: Codable, JSONEncodable, Hashable {

    /** The given year */
    public var year: String
    /** List of months of the given year that donation receipt summary is available for */
    public var months: [GivingCustomerDonationReceiptSummaryMonth]

    public init(year: String, months: [GivingCustomerDonationReceiptSummaryMonth]) {
        self.year = year
        self.months = months
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case year
        case months
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(year, forKey: .year)
        try container.encode(months, forKey: .months)
    }
}

