//
// GivingCustomerDonationReceiptSummaryGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GivingCustomerDonationReceiptSummaryGroup: Codable, JSONEncodable, Hashable {

    /** The group title to display, based on the provided grouping setting */
    public var groupTitle: String
    /** List of receipts in the given group */
    public var receipts: [GivingCustomerDonationReceiptSummaryReceipt]

    public init(groupTitle: String, receipts: [GivingCustomerDonationReceiptSummaryReceipt]) {
        self.groupTitle = groupTitle
        self.receipts = receipts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case groupTitle
        case receipts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(groupTitle, forKey: .groupTitle)
        try container.encode(receipts, forKey: .receipts)
    }
}

