//
// GivingCharityCategoryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GivingCharityCategoryResponse: Codable, JSONEncodable, Hashable {

    /** Unique ID of the charity category. */
    public var id: String
    /** Name of the charity category. */
    public var name: String
    /** Background image. */
    public var backgroundImageUrl: String?
    /** Whether this category is client scoped */
    public var clientScoped: Bool?
    /** List of Giving Charities belonging to this category */
    public var charities: [GivingCharityResponse]?

    public init(id: String, name: String, backgroundImageUrl: String? = nil, clientScoped: Bool? = nil, charities: [GivingCharityResponse]? = nil) {
        self.id = id
        self.name = name
        self.backgroundImageUrl = backgroundImageUrl
        self.clientScoped = clientScoped
        self.charities = charities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case backgroundImageUrl
        case clientScoped
        case charities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(backgroundImageUrl, forKey: .backgroundImageUrl)
        try container.encodeIfPresent(clientScoped, forKey: .clientScoped)
        try container.encodeIfPresent(charities, forKey: .charities)
    }
}

