//
// InstantImpact.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A single socially responsible Instant Impact from performing a financial transaction. */
public struct InstantImpact: Codable, JSONEncodable, Hashable {

    public var category: InstantImpactCategory
    /** Point value for associated Instant Impact Category. */
    public var impact: Int
    /** Dollar value for associated Instant Impact Category. */
    public var amountDonated: Double?
    public var transaction: DepositoryOrCreditTransaction?

    public init(category: InstantImpactCategory, impact: Int, amountDonated: Double? = nil, transaction: DepositoryOrCreditTransaction? = nil) {
        self.category = category
        self.impact = impact
        self.amountDonated = amountDonated
        self.transaction = transaction
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case category
        case impact
        case amountDonated
        case transaction
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(category, forKey: .category)
        try container.encode(impact, forKey: .impact)
        try container.encodeIfPresent(amountDonated, forKey: .amountDonated)
        try container.encodeIfPresent(transaction, forKey: .transaction)
    }
}

