//
// InstantImpactCategoryRewardSelection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Instant Impact Category Charity and Reward Unit selection for a Client */
public struct InstantImpactCategoryRewardSelection: Codable, JSONEncodable, Hashable {

    public var instantImpactCategoryId: String
    public var charityId: String
    public var charityRewardUnitId: String?
    public var rewardUnitId: String

    public init(instantImpactCategoryId: String, charityId: String, charityRewardUnitId: String? = nil, rewardUnitId: String) {
        self.instantImpactCategoryId = instantImpactCategoryId
        self.charityId = charityId
        self.charityRewardUnitId = charityRewardUnitId
        self.rewardUnitId = rewardUnitId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case instantImpactCategoryId
        case charityId
        case charityRewardUnitId
        case rewardUnitId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(instantImpactCategoryId, forKey: .instantImpactCategoryId)
        try container.encode(charityId, forKey: .charityId)
        try container.encodeIfPresent(charityRewardUnitId, forKey: .charityRewardUnitId)
        try container.encode(rewardUnitId, forKey: .rewardUnitId)
    }
}

