//
// NotificationCountResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NotificationCountResponse: Codable, JSONEncodable, Hashable {

    static let notificationsCountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Number of new notifications */
    public var notificationsCount: Int

    public init(notificationsCount: Int) {
        self.notificationsCount = notificationsCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notificationsCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(notificationsCount, forKey: .notificationsCount)
    }
}

