//
// NotificationDetailsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NotificationDetailsResponse: Codable, JSONEncodable, Hashable {

    /** Unique notification id */
    public var id: String
    /** Date and time when notification got created */
    public var createdAtDate: Date?
    /** Notification type */
    public var type: String?
    /** Notification HTML content as an object */
    public var content: AnyCodable?
    /** Has notification been previously viewed by customer */
    public var isViewed: Bool?

    public init(id: String, createdAtDate: Date? = nil, type: String? = nil, content: AnyCodable? = nil, isViewed: Bool? = nil) {
        self.id = id
        self.createdAtDate = createdAtDate
        self.type = type
        self.content = content
        self.isViewed = isViewed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdAtDate
        case type
        case content
        case isViewed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(createdAtDate, forKey: .createdAtDate)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(content, forKey: .content)
        try container.encodeIfPresent(isViewed, forKey: .isViewed)
    }
}

