//
// Product.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Client-selectable products. */
public enum Product: String, Codable, CaseIterable {
    case giving = "GIVING"
    case everydayImpact = "EVERYDAY_IMPACT"
}
