//
// RewardLimits.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RewardLimits: Codable, JSONEncodable, Hashable {

    public var perTransaction: Double?
    public var perMonth: Double?
    public var perYear: Double?

    public init(perTransaction: Double? = nil, perMonth: Double? = nil, perYear: Double? = nil) {
        self.perTransaction = perTransaction
        self.perMonth = perMonth
        self.perYear = perYear
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case perTransaction
        case perMonth
        case perYear
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(perTransaction, forKey: .perTransaction)
        try container.encodeIfPresent(perMonth, forKey: .perMonth)
        try container.encodeIfPresent(perYear, forKey: .perYear)
    }
}

