//
// RoundUpSelections.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Available selections for the user sponsored reward type */
public enum RoundUpSelections: String, Codable, CaseIterable {
    case dollar = "dollar"
    case fiveDollars = "five_dollars"
    case tenDollars = "ten_dollars"
}
