//
// SelectedImpactCategoriesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SelectedImpactCategoriesRequest: Codable, JSONEncodable, Hashable {

    public var categories: [ExtendedImpactCategoryRewardSelection]
    public var anonymousDonor: Bool?

    public init(categories: [ExtendedImpactCategoryRewardSelection], anonymousDonor: Bool? = nil) {
        self.categories = categories
        self.anonymousDonor = anonymousDonor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categories
        case anonymousDonor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(categories, forKey: .categories)
        try container.encodeIfPresent(anonymousDonor, forKey: .anonymousDonor)
    }
}

