//
// SettingsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SettingsResponse: Codable, JSONEncodable, Hashable {

    public var settings: [[String: AnyCodable]]

    public init(settings: [[String: AnyCodable]]) {
        self.settings = settings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case settings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(settings, forKey: .settings)
    }
}

