//
// SocialResponsibilityInstantImpactSummaryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Single customer&#39;s Instant Impact report */
public struct SocialResponsibilityInstantImpactSummaryResponse: Codable, JSONEncodable, Hashable {

    /** ID of most recently rewarded unit */
    public var mostRecentRewardedUnitId: String?
    public var instantImpact: [SocialResponsibilityInstantImpactSummaryItem]

    public init(mostRecentRewardedUnitId: String? = nil, instantImpact: [SocialResponsibilityInstantImpactSummaryItem]) {
        self.mostRecentRewardedUnitId = mostRecentRewardedUnitId
        self.instantImpact = instantImpact
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mostRecentRewardedUnitId
        case instantImpact
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mostRecentRewardedUnitId, forKey: .mostRecentRewardedUnitId)
        try container.encode(instantImpact, forKey: .instantImpact)
    }
}

