//
// SortResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SortResponse: Codable, JSONEncodable, Hashable {

    /** Did sort by any field */
    public var empty: Bool
    /** Are the results not sorted */
    public var unsorted: Bool
    /** Are the results sorted */
    public var sorted: Bool

    public init(empty: Bool, unsorted: Bool, sorted: Bool) {
        self.empty = empty
        self.unsorted = unsorted
        self.sorted = sorted
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case empty
        case unsorted
        case sorted
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(empty, forKey: .empty)
        try container.encode(unsorted, forKey: .unsorted)
        try container.encode(sorted, forKey: .sorted)
    }
}

