//
// SummaryDonationType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Donation recurrence type for donation summary - all, one-time only or recurring only. */
public enum SummaryDonationType: String, Codable, CaseIterable {
    case all = "ALL"
    case oneTime = "ONE_TIME"
    case recurring = "RECURRING"
}
