//
// SummaryTimePeriod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Possible periods to choose from for Instant Impact reports */
public enum SummaryTimePeriod: String, Codable, CaseIterable {
    case allTime = "ALL_TIME"
    case lastMonth = "LAST_MONTH"
}
