//
// TermsAndConditionsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TermsAndConditionsResponse: Codable, JSONEncodable, Hashable {

    public var copy: String?

    public init(copy: String? = nil) {
        self.copy = copy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case copy
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(copy, forKey: .copy)
    }
}

