//
// TransactionProcessResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionProcessResponse: Codable, JSONEncodable, Hashable {

    /** Permanent, unique transaction id. Must survive changes to pending status or amount. */
    public var transactionId: String
    public var impact: TransactionImpactResponse

    public init(transactionId: String, impact: TransactionImpactResponse) {
        self.transactionId = transactionId
        self.impact = impact
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transactionId
        case impact
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(transactionId, forKey: .transactionId)
        try container.encode(impact, forKey: .impact)
    }
}

