//
// TransactionStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Transaction authorization status */
public enum TransactionStatus: String, Codable, CaseIterable {
    case pending = "PENDING"
    case settled = "SETTLED"
}
