//
// TransactionProcessRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionProcessRequest: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case sync = "sync"
        case async = "async"
    }
    /** Processing Type */
    public var type: ModelType
    public var transaction: DepositoryOrCreditTransaction
    public var customerInformation: DonorInformation

    public init(type: ModelType, transaction: DepositoryOrCreditTransaction, customerInformation: DonorInformation) {
        self.type = type
        self.transaction = transaction
        self.customerInformation = customerInformation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case transaction
        case customerInformation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(transaction, forKey: .transaction)
        try container.encode(customerInformation, forKey: .customerInformation)
    }
}

