//
// UpdateFailedDonationCharityRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateFailedDonationCharityRequest: Codable, JSONEncodable, Hashable {

    /** Unique Notification ID */
    public var notificationId: String?
    /** Unique Donation ID */
    public var donationId: String?
    /** Unique Charity ID */
    public var charityId: String?

    public init(notificationId: String? = nil, donationId: String? = nil, charityId: String? = nil) {
        self.notificationId = notificationId
        self.donationId = donationId
        self.charityId = charityId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notificationId
        case donationId
        case charityId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(notificationId, forKey: .notificationId)
        try container.encodeIfPresent(donationId, forKey: .donationId)
        try container.encodeIfPresent(charityId, forKey: .charityId)
    }
}

